//SCALE
//$scale 0

//ORIGIN
//$origin 0 0 0 0

//MODELNAME
$modelname "weapons\tfa_grovez\shells\545x39\7n6\545x39_shell.mdl"

//STATICPROP
$staticprop

//MODEL
$model "shell" "545x39_shell.smd"

//ZALOOPA
$illumposition 0 0 0
$mostlyopaque

//CDMATERIALS
$cdmaterials "models\weapons\tfa_grovez\ammo\545x39\"

//ATTACHMENTS
$attachment "1" "root" 0 -2.25 0 rotate 0 -90 0

//IDLE
$sequence idle "545x39_shell.smd"